name: brazilian_perfect
description: "organizador de torneios de xadrez"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.8.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.14.1
  #path: ^1.9.0
  intl: ^0.19.0
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  localstorage: ^5.0.0
  json_annotation: ^4.9.0
  tuple: ^2.0.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Scaatliches
      fonts:
        - asset: assets/fonts/ScaatlichesRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400

flutter_launcher_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true
